cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-igp-test"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
hyperlane-core = { path = "../../../hyperlane-core" }
access-control = { path = "../../libraries/access-control" }
account-utils = { path = "../../libraries/account-utils" }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }
borsh.workspace = true
solana-program.workspace = true
hyperlane-sealevel-igp = { path = "../hyperlane-sealevel-igp" }

solana-program-test.workspace = true
solana-sdk.workspace = true
hyperlane-test-utils = { path = "../../libraries/test-utils" }

[profile.release]
overflow-checks = true
