cargo-features = ["workspace-inheritance"]

[package]
name = "access-control"
version = "0.1.0"
edition = "2021"

[dependencies]
solana-program.workspace = true

[dev-dependencies]

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
overflow-checks = true
