[package]
name = "hyperlane-sealevel-client"
version = "0.1.0"
edition = "2021"

[dependencies]
borsh = "0.9"
clap = { version = "4", features = ["derive"] }
hyperlane-sealevel-mailbox = { path = "../programs/mailbox" }
lazy_static = "1.4"
pretty_env_logger = "0.4"
solana-sdk = "=1.14.3"
solana-client = "=1.14.3"
solana-cli-config = "=1.14.3"
solana-clap-utils = "=1.14.3"
