# Configs and artifacts for the deployment of Hyperlane Warp Routes
# Between injective and inevm
description: Hyperlane Warp Route artifacts
timestamp: '2024-09-19T16:00:00.000Z'
deployer: Abacus Works (Hyperlane)
data:
  config:
    solanamainnet:
      protocolType: sealevel
      type: native
      hypAddress: '8DtAGQpcMuD5sG3KdxDy49ydqXUggR1LQtebh2TECbAc'
      tokenCoinGeckoId: solana
      name: Solana
      symbol: SOL
      decimals: 9
    eclipsemainnet:
      protocolType: sealevel
      type: synthetic
      hypAddress: 'FJu4E1BDYKVg7aTWdwATZRUvytJZ8ZZ2gQuvPfMWAz9y'
      tokenAddress: 'BeRUj3h7BqkbdfFU7FBNYbodgf8GCHodzKvF9aVjNNfL'
      isSpl2022: true
      name: Solana
      symbol: SOL
      decimals: 9
