# Configs and artifacts for the deployment of Hyperlane Warp Routes
# Between injective and inevm
description: Hyperlane Warp Route artifacts
timestamp: '2024-02-06T16:00:00.000Z'
deployer: Abacus Works (Hyperlane)
data:
  config:
    ethereum:
      protocolType: ethereum
      type: collateral
      hypAddress: '0xab852e67bf03E74C89aF67C4BA97dd1088D3dA19'
      tokenAddress: '0xdac17f958d2ee523a2206206994597c13d831ec7' # USDT
      tokenCoinGeckoId: tether
      name: Tether USD
      symbol: USDT
      decimals: 6
    inevm:
      protocolType: ethereum
      type: synthetic
      hypAddress: '0x97423A68BAe94b5De52d767a17aBCc54c157c0E5'
      name: Tether USD
      symbol: USDT
      decimals: 6
