# Configs and artifacts for the deployment of Hyperlane Warp Routes
# Between injective and inevm
description: Hyperlane Warp Route artifacts
timestamp: '2024-01-31T16:00:00.000Z'
deployer: Abacus Works (Hyperlane)
data:
  config:
    injective:
      protocolType: cosmos
      type: native
      hypAddress: inj1mv9tjvkaw7x8w8y9vds8pkfq46g2vcfkjehc6k
      tokenCoinGeckoId: injective-protocol
      name: Injective Coin
      symbol: INJ
      decimals: 18
      ibcDenom: inj
    inevm:
      protocolType: ethereum
      type: native
      hypAddress: '0x26f32245fCF5Ad53159E875d5Cae62aEcf19c2d4'
      name: Injective coin
      symbol: INJ
      decimals: 18
