# Configs and artifacts for the deployment of Hyperlane Warp Routes
# Between neutron and mantapacific
description: Hyperlane Warp Route artifacts
timestamp: '2023-09-23T16:00:00.000Z'
deployer: Abacus Works (Hyperlane)
data:
  config:
    neutron:
      protocolType: cosmos
      type: collateral
      hypAddress: neutron1ch7x3xgpnj62weyes8vfada35zff6z59kt2psqhnx9gjnt2ttqdqtva3pa
      tokenAddress: ibc/773B4D0A3CD667B2275D5A4A7A2F0909C0BA0F4059C0B9181E680DDF4965DCC7
      tokenCoinGeckoId: celestia
      name: Celestia
      symbol: TIA
      decimals: 6
    mantapacific:
      protocolType: ethereum
      type: synthetic
      hypAddress: '0x6Fae4D9935E2fcb11fC79a64e917fb2BF14DaFaa'
      name: Celestia
      symbol: TIA
      decimals: 6
