cargo-features = ["workspace-inheritance"]

[package]
name = "hyperlane-sealevel-test-send-receiver"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []
test-client = ["dep:solana-program-test", "dep:solana-sdk", "dep:hyperlane-test-utils", "dep:spl-noop"]

[dependencies]
borsh.workspace = true
solana-program-test = { workspace = true, optional = true }
solana-program.workspace = true
solana-sdk = { workspace = true, optional = true }
spl-noop = { workspace = true, optional = true }

account-utils = { path = "../../libraries/account-utils" }
hyperlane-sealevel-mailbox = { path = "../mailbox", features = ["no-entrypoint"] }
hyperlane-sealevel-message-recipient-interface = { path = "../../libraries/message-recipient-interface" }
hyperlane-test-utils = { path = "../../libraries/test-utils", optional = true }
serializable-account-meta = { path = "../../libraries/serializable-account-meta" }

[lib]
crate-type = ["cdylib", "lib"]

[profile.release]
overflow-checks = true
